baseURL = "/"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "KPMG Clara"
theme = "hugo-theme-learn"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

[params]
  description = "Clara SOP"
  author = "Mathieu Cornic"
  showVisitedLinks = false
  disableBreadcrumb = false
  disableNextPrev = false
  disableLanguageSwitchingButton = true
  ordersectionby = "weight"


[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
title = "SOP"
weight = 1
languageName = "English"
